all:
	@make -C ITKUtils 
	@make -C DICOMTools
	@make -C ContourTools
	@make -C FeatureExtraction
	@make -C GrowCutSegmentation

clean:
	@make -C ITKUtils clean
	@make -C DICOMTools clean
	@make -C ContourTools clean
	@make -C FeatureExtraction clean
	@make -C GrowCutSegmentation clean

	@echo "Clean up all builds!!"

